- id: j38aWAKEUP
  alias: Wake up
  mode: restart
  trigger:
    - platform: time
      at: "06:15:00"
  variables:
    delay: 600
  action:
    - condition: state
      entity_id: light.livingroom1
      state: 'off'
    - scene: scene.latenight
    - delay: 3
    - service: light.turn_on
      target:
        entity_id:
          - light.kitchen_lights
          - light.livingroom_lights
      data:
        brightness: 255
        rgb_color: [255,0,0]
    - delay: "{{ delay }}"

    - service: light.turn_on
      target:
        entity_id:
          - light.kitchen_lights
      data:
        brightness: 25 
        color_temp: 370 
    - service: light.turn_on
      target:
        entity_id:
          - light.livingroom_lights
      data:
        brightness: 150 
        color_temp: 500 
    - delay: "{{ delay }}"

    - service: light.turn_on
      target:
        entity_id:
          - light.kitchen_lights
      data:
        brightness: 255 
        color_temp: 370
    - service: light.turn_on
      target:
        entity_id:
          - light.livingroom_lights
      data:
        brightness: 255 
        color_temp: 500
    - delay: "{{ delay }}"

    - service: light.turn_on
      target:
        entity_id:
          - light.kitchen_lights
          - light.livingroom_lights
      data:
        brightness: 255 
        color_temp: 154 
    - delay: "{{ delay }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day
    - delay: "{{ delay*2 }}"

    - scene: scene.day

- id: j38aWINDDOWN
  alias: Wind down
  mode: restart
  trigger:
    - platform: time
      at: "15:00:00"
  variables:
    delay: 3600
  action:
    - condition: state
      entity_id: switch.kitchen_flood
      state: 'on'
    - scene: scene.afternoon
    - delay: "{{ delay*2 }}"

    - scene: scene.evening
    - delay: "{{ delay }}"

    - scene: scene.night
    - delay: "{{ delay }}"

    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen1
          - light.livingroom1
    - delay: "{{ delay }}"

    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen2
          - light.bedroom
    - delay: "{{ delay }}"

    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen3
          - light.livingroom2
    - delay: "{{ delay }}"

    - service: light.turn_off
      target:
        entity_id:
          - light.hallway
    - delay: "{{ delay }}"

    - scene: scene.latenight
    - delay: "{{ delay }}"

    - scene: scene.latenight
    - delay: "{{ delay }}"

    - scene: scene.latenight
    - delay: "{{ delay }}"

    - scene: scene.latenight
    - delay: "{{ delay }}"

    - scene: scene.latenight
    - delay: "{{ delay }}"

    - scene: scene.latenight







